### ISSUE TITLE
Problem to display information

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/technical.openmobilealliance.org#158]
@rubystream, something happened when deploying the new functionality to the production.
The content from the information file is not displayed at all.

I plan to present to the groups tomorrow at 8:00am PDT, 5pm your time. 

<img width="1219" alt="image" src="https://github.com/OpenMobileAlliance/technical.openmobilealliance.org/assets/3258579/fcf96986-5c24-49ed-afb0-613709c4b66a">

**Comment by rubystream** [comment]
It is resolved in 2058ddec8ac970f877966e3badb4ac9a4ce817ed and merge in gh-pages 7ba4e17dc080a164fec865aa2157629e299cd676.

The issue was most probably in difference how GitHub pages regard the files with names that starts with `_` (underline) as it can be regarded as hidden file that should not be presented.

**Comment by jpradocueva** [comment]
problem resolved.
