### ISSUE TITLE
Pending Functionality in the Enablers table

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/technical.openmobilealliance.org#74]
- [ ] ability to expand all the Enablers versions or only the latest versions Approved and Candidates (above an approved release)

**Comment by rubystream** [comment]
@jpradocueva the rules for `display` attribute in adjusted for **Show All** in version 0401e9f6aa2f8326539d30d7d8cd489942019e65

Note:
I noticed that **HTML_Deployment_Suite** has no versions whatsoever. There are none in the `enabler.json` file as well. This is due the specific format of folders at  its [FTP site ](https://www.openmobilealliance.org/release/HTML_Deployment_Suite/).
Perhaps, in order to resolve this inconsistency the data can be added manually in the `enabler.json` file. WDYT

**Comment by jpradocueva** [comment]
@rubystream this issue that you are raising is an example of the problems we are encountering with this FTP. The content of the EVP, and ETS folders are structured differently from the Enablers. We have the same problem with the LwM2M folder, which also contains these two folders ETS and EVP. 
We decided to insert a link to each one of these folders as a resourceType (EVP, ETS and TFP). In this way we can expose the content as the files inside of these folders are not group in subfolders as the Enablers.

![image](https://user-images.githubusercontent.com/3258579/185665122-fa1bb317-4152-4cc3-8223-09be86a1acd9.png)

**Comment by jpradocueva** [comment]
@jmudge please verify if all the issues have been resolved.
I have done a quick check and I don't see any outstanding problem, but you have been doing thorough checks and you may find something else.

**Comment by jmudge** [comment]
@jpradocueva these issues have been resolved.

**Comment by jpradocueva** [comment]
@jmudge thanks John.

**Comment by jmudge** [comment]
@jpradocueva you're welcome!
